version: '3'

services:
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 'password'
    ports:
      - 6543:5432
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data:cached
